my_string = input(' Эта строка с произвольным текстом, введите что-нибудь (с пробелами): ')
print('В введёном вами тексте (включая пробелы): ', len(my_string), 'символов')
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])